Repository Yashgabani845/hiring-portal, pull requests merged in 2024-10, with the labels that each got.

#18 redirect to home page functionality
  hiring-portal/src/Components/Navbar.jsx
Labels: gssoc-extd

#33 Improve the job section ui
  hiring-portal/src/CSS/job.css
  hiring-portal/src/Components/Job.jsx
Labels: level2, gssoc-ext

#34 added logos and icon
  hiring-portal/public/favicon.ico
  hiring-portal/public/favicon2.ico
  hiring-portal/public/index.html
  hiring-portal/src/Components/Signin.jsx
  hiring-portal/src/logo.png
Labels: level2, gssoc-ext

#39 added hover & color change effects to social-icons
  hiring-portal/src/CSS/footer.css
  hiring-portal/src/Components/Footer.jsx
Labels: level1, gssoc-ext

#42 Make home page reponsive
  hiring-portal/src/CSS/footer.css
  hiring-portal/src/CSS/herosection.css
  hiring-portal/src/CSS/interview.css
  hiring-portal/src/CSS/middleview.css
  hiring-portal/src/CSS/navbar.css
  hiring-portal/src/CSS/postview.css
  hiring-portal/src/Components/Footer.jsx
  hiring-portal/src/Components/Homepage.jsx
  hiring-portal/src/Components/MiddleView.jsx
  hiring-portal/src/Components/Navbar.jsx
Labels: level2, gssoc-ext

#109 added-hover-#67
  hiring-portal/package-lock.json
  hiring-portal/src/CSS/navbar.css
Labels: level1, gssoc-ext

#116 [Feature] Automating the Project strucutre.
  .github/scripts/update-structure.py
  .github/workflows/Update-structure.yml
  README.md
  repo_structure.txt
Labels: level 2, gssoc-ext, hactoberfest, hactoberfest-accepted

#119 Improved the css of about us page
  hiring-portal/src/App.js
  hiring-portal/src/CSS/about.css
  hiring-portal/src/Components/About.jsx
  hiring-portal/src/Components/Navbar.jsx
  package-lock.json
Labels: level1, gssoc-ext, hactoberfest, hactoberfest-accepted

#125 Added full functional blog page
  hiring-portal/Backend/controllers/blogController.js
  hiring-portal/Backend/models/Blog.js
  hiring-portal/Backend/routes/blogRoutes.js
  hiring-portal/Backend/server.js
  hiring-portal/src/App.js
  hiring-portal/src/CSS/blog.css
  hiring-portal/src/CSS/createBlog.css
  hiring-portal/src/CSS/readMoreBlog.css
  hiring-portal/src/Components/BlogPage.jsx
  hiring-portal/src/Components/CreateBlog.jsx
  hiring-portal/src/Components/Navbar.jsx
  hiring-portal/src/Components/ReadMoreBlog.jsx
Labels: enhancement, level3, gssoc-ext, hactoberfest, hactoberfest-accepted

#121 Handle form submission and also show error msg if any
  hiring-portal/Backend/.env
  hiring-portal/Backend/controllers/contactController.js
  hiring-portal/Backend/models/Contact.js
  hiring-portal/Backend/routes/contactRoutes.js
  hiring-portal/Backend/server.js
  hiring-portal/src/CSS/contactus.css
  hiring-portal/src/Components/Contactus.jsx
  hiring-portal/src/Components/Navbar.jsx
Labels: level3, gssoc-ext, hactoberfest, hactoberfest-accepted

#140 Added terms and condition page
  hiring-portal/src/App.js
  hiring-portal/src/CSS/termsAndConditions.css
  hiring-portal/src/Components/Footer.jsx
  hiring-portal/src/Components/TermsAndConditions.jsx
Labels: level1, gssoc-ext, hacktoberfest, hacktoberfest-accepted

#139 Added chatbot
  hiring-portal/.gitignore
  hiring-portal/package-lock.json
  hiring-portal/package.json
  hiring-portal/src/App.js
  hiring-portal/src/CSS/chatbot.css
  hiring-portal/src/Components/Chatbot.jsx
  hiring-portal/src/Components/Contactus.jsx
  hiring-portal/src/Components/Navbar.jsx
  hiring-portal/src/assests/contact.png
  hiring-portal/src/index.js
  package-lock.json
Labels: level3, gssoc-ext, hacktoberfest, hacktoberfest-accepted

#158 Added bookmarks api on backend
  hiring-portal/Backend/controllers/bookmarksController.js
  hiring-portal/Backend/models/Bookmarks.js
  hiring-portal/Backend/routes/bookmarksRoute.js
  hiring-portal/Backend/server.js
Labels: level2, gssoc-ext, hacktoberfest, hacktoberfest-accepted

#161 made job page responsive issue #157
  hiring-portal/src/CSS/job.css
  hiring-portal/src/Components/Job.jsx
Labels: level2, gssoc-ext, hacktoberfest, hacktoberfest-accepted

#160 Added Contributor to readme.md
  README.md
Labels: level1, gssoc-ext, hacktoberfest, hacktoberfest-accepted

#217 Fixes:#209 - adding Gssoc and Hacktoberfest banner.
  README.md
Labels: documentation, level1, gssoc-ext, hacktoberfest, hacktoberfest-accepted

#207 Added AI based chatbot
  hiring-portal/src/CSS/backtotop.css
  hiring-portal/src/Components/Footer.jsx
Labels: level3, gssoc-ext, hacktoberfest, hacktoberfest-accepted

#233 Done enhancement and also added some new sections
  Contributing.md
Labels: level1, gssoc-ext, hacktoberfest, hacktoberfest-accepted

#218 Fixed: #182 NavBar Icon Link in mobile view
  hiring-portal/src/CSS/navbar.css
  hiring-portal/src/Components/Navbar.jsx
Labels: level1, gssoc-ext, hacktoberfest, hacktoberfest-accepted

#236 added email functionality
  hiring-portal/Backend/controllers/contactController.js
  hiring-portal/Backend/routes/contactRoutes.js
  hiring-portal/package-lock.json
  hiring-portal/src/Components/Contactus.jsx
Labels: level2, gssoc-ext, hacktoberfest, hacktoberfest-accepted

#235 Update README.md added Stargazers and Forkers section to readme.md
  README.md
Labels: level1, gssoc-ext, hacktoberfest, hacktoberfest-accepted

#201 Add Docker setup
  hiring-portal/Backend/Dockerfile
  hiring-portal/docker-compose.yml
  hiring-portal/src/Dockerfile
Labels: level2, gssoc-ext, hacktoberfest, hacktoberfest-accepted

#249 Add toast to Employer/Post Job
  hiring-portal/package-lock.json
  hiring-portal/package.json
  hiring-portal/src/App.js
  hiring-portal/src/Components/CreateBlog.jsx
  hiring-portal/src/Components/Navbar.jsx
Labels: level2, gssoc-ext, hacktoberfest, hacktoberfest-accepted

#262 toast containers added
  hiring-portal/src/App.js
  hiring-portal/src/Components/Profile.jsx
  hiring-portal/src/Components/Signup.jsx
Labels: level1, gssoc-ext, hacktoberfest, hacktoberfest-accepted

#240 Add resume screening Feature
  hiring-portal/package-lock.json
  hiring-portal/package.json
  hiring-portal/src/App.js
  hiring-portal/src/Components/Navbar.jsx
  hiring-portal/src/Components/ResumeScreening.jsx
Labels: level 3, gssoc-ext, hacktoberfest, hacktoberfest-accepted

#270 Requiredfields check added
  hiring-portal/Backend/controllers/applicationController.js
  hiring-portal/package-lock.json
  hiring-portal/package.json
  hiring-portal/src/Components/ApplicationForm.jsx
Labels: level2, gssoc-ext, hacktoberfest, hacktoberfest-accepted

#278 Fix Applications Page
  hiring-portal/Backend/middlewares/authMiddleware.js
  hiring-portal/Backend/routes/blogRoutes.js
  hiring-portal/src/CSS/ApplicationForm.css
  hiring-portal/src/Components/ApplicationForm.jsx
  package-lock.json
Labels: level2, gssoc-ext, hacktoberfest, hacktoberfest-accepted

#283 ADD Forgot Password
  hiring-portal/Backend/.env.example
  hiring-portal/Backend/controllers/forgotPasswordController.js
  hiring-portal/Backend/models/User.js
  hiring-portal/Backend/routes/userRoutes.js
  hiring-portal/Backend/server.js
  hiring-portal/package-lock.json
  hiring-portal/package.json
  hiring-portal/src/App.js
  hiring-portal/src/Components/ForgotPassword.jsx
  hiring-portal/src/Components/Signin.jsx
Labels: level3, gssoc-ext, hacktoberfest, hacktoberfest-accepted

#256 Added Error Handling and File Format Validation Messages (Issue #254)
  hiring-portal/Backend/ats.py
Labels: level2, gssoc-ext, hacktoberfest, hacktoberfest-accepted
