Repository Yashgabani845/hiring-portal, pull requests merged in 2024-11, with the labels that each got.

#299 added animation when no blogs found
  PROJECT_STRUCTURE.md
  hiring-portal/Backend/.env
  hiring-portal/package-lock.json
  hiring-portal/package.json
  hiring-portal/src/App.js
  hiring-portal/src/Components/ApplicationForm.jsx
  hiring-portal/src/Components/BlogPage.jsx
  hiring-portal/src/assests/emptyanimation.json
  repo_structure.txt
Labels: level2, gssoc-ext, hacktoberfest, hacktoberfest-accepted

#301 responsive owner page and added animation
  hiring-portal/src/App.js
  hiring-portal/src/CSS/employer.css
  hiring-portal/src/CSS/navbar.module.css
  hiring-portal/src/Components/Employer.jsx
  hiring-portal/src/Components/Navbar.jsx
Labels: level 3, gssoc-ext, hacktoberfest, hacktoberfest-accepted

#303 fixed Home page error of faq section and other small issues
  PROJECT_STRUCTURE.md
  hiring-portal/src/Components/Faqs.jsx
  hiring-portal/src/Components/MiddleView.jsx
  repo_structure.txt
Labels: level2, gssoc-ext, hacktoberfest, hacktoberfest-accepted

#296 Added mail feature on contact us form for instant reply
  hiring-portal/Backend/.env
  hiring-portal/Backend/.env.example
  hiring-portal/Backend/controllers/contactController.js
  hiring-portal/Backend/routes/contactRoutes.js
  hiring-portal/Backend/sendMail.js
  hiring-portal/src/App.js
  hiring-portal/src/Components/ApplicationForm.jsx
  hiring-portal/src/Components/Contactus.jsx
Labels: level3, gssoc-ext, hacktoberfest, hacktoberfest-accepted

#272 Blog Details Page
  hiring-portal/src/App.js
  hiring-portal/src/Components/BlogDetailsPage.jsx
Labels: level2, gssoc-ext, hacktoberfest, hacktoberfest-accepted

#308 added Private route in create blog page
  PROJECT_STRUCTURE.md
  hiring-portal/src/App.js
  hiring-portal/src/Components/Spinner.jsx
  hiring-portal/src/PrivateRoute.jsx
  repo_structure.txt
Labels: level3, gssoc-ext, hacktoberfest, hacktoberfest-accepted

#319 seperated the json in another folder
  hiring-portal/src/Components/ApplicationForm.jsx
  hiring-portal/src/Components/EditProfile.jsx
  hiring-portal/src/Components/JobPostForm.jsx
  hiring-portal/src/Components/Signup.jsx
  hiring-portal/src/Json/colleges.json
  hiring-portal/src/Json/country.json
  hiring-portal/src/Json/course.json
  hiring-portal/src/Json/skills.json
  hiring-portal/src/Json/upJobs.json
Labels: level2, gssoc-ext, hacktoberfest, hacktoberfest-accepted

#317 Added Terms of use page
  hiring-portal/src/App.js
  hiring-portal/src/CSS/TermsOfUse.module.css
  hiring-portal/src/Components/Footer.jsx
  hiring-portal/src/Components/TermsOfUse.jsx
Labels: level2, gssoc-ext, hacktoberfest, hacktoberfest-accepted

#320 Added sign in with google feature
  hiring-portal/src/CSS/SigninWithGoogle.module.css
  hiring-portal/src/CSS/signin.css
  hiring-portal/src/Components/Footer.jsx
  hiring-portal/src/Components/SignInWithGoogle.jsx
  hiring-portal/src/Components/Signin.jsx
  hiring-portal/src/firebase/firebase.js
Labels: level 3, gssoc-ext, hacktoberfest, hacktoberfest-accepted

#318 Added frontend and backend for feedback form
  hiring-portal/Backend/controllers/feedbackController.js
  hiring-portal/Backend/models/feedback.js
  hiring-portal/Backend/routes/feedbackRoutes.js
  hiring-portal/Backend/server.js
  hiring-portal/src/App.js
  hiring-portal/src/CSS/Feedback.module.css
  hiring-portal/src/Components/Feedback.jsx
Labels: level 3, gssoc-ext, hacktoberfest, hacktoberfest-accepted

#323 Added open issue card in both light and dark theme
  hiring-portal/src/CSS/contributor.css
  hiring-portal/src/Components/ContributorPage.jsx
Labels: level3, gssoc-ext, hacktoberfest, hacktoberfest-accepted

#325 Added toaster on click to posting job
  hiring-portal/src/Components/Navbar.jsx
Labels: level2, gssoc-ext, hacktoberfest, hacktoberfest-accepted

#324 Implemented CURD backend Api for total visitor count
  hiring-portal/Backend/controllers/visitorController.js
  hiring-portal/Backend/models/Visitor.js
  hiring-portal/Backend/routes/visitorRoutes.js
  hiring-portal/Backend/server.js
  hiring-portal/src/Components/Footer.jsx
  hiring-portal/src/Components/VisitorCount.jsx
Labels: level2, gssoc-ext, hacktoberfest, hacktoberfest-accepted

#333 added animation in the jobs page
  hiring-portal/src/Components/JobGrid.jsx
  hiring-portal/src/assests/loading.json
Labels: level2, gssoc-ext, hacktoberfest, hacktoberfest-accepted

#339 Enhance the styling of testimonial page and maked it autoscrollable
  hiring-portal/src/Components/Testimonial.jsx
Labels: level1, gssoc-ext, hacktoberfest, hacktoberfest-accepted

#366 Implement Stories Page for User Job Interview Experience Sharing ✨🚀
  hiring-portal/src/App.js
  hiring-portal/src/CSS/Stories.module.css
  hiring-portal/src/Components/Footer.jsx
  hiring-portal/src/Components/Stories.jsx
Labels: level 3, gssoc-ext, hacktoberfest, hacktoberfest-accepted

#362 added loader to sign in page
  PROJECT_STRUCTURE.md
  hiring-portal/Backend/controllers/applicationController.js
  hiring-portal/src/Components/SignInWithGoogle.jsx
  hiring-portal/src/Components/Signin.jsx
  repo_structure.txt
Labels: level2, gssoc-ext, hacktoberfest, hacktoberfest-accepted

#358 add Pagination in blogs page
  hiring-portal/Backend/controllers/blogController.js
  hiring-portal/Backend/routes/blogRoutes.js
  hiring-portal/src/App.js
  hiring-portal/src/CSS/blog.module.css
  hiring-portal/src/Components/BlogPage.jsx
Labels: level3, gssoc-ext, hacktoberfest, hacktoberfest-accepted

#357 Refactor Navbar for Improved Usability and Design ✨
  hiring-portal/src/CSS/navbar.module.css
  hiring-portal/src/Components/Navbar.jsx
Labels: level2, gssoc-ext, hacktoberfest, hacktoberfest-accepted

#368 Build Backend for Stories Page: Implement POST and GET Routes ✨🚀
  hiring-portal/Backend/controllers/postsController.js
  hiring-portal/Backend/models/postModel.js
  hiring-portal/Backend/routes/storiesRoutes.js
  hiring-portal/Backend/server.js
  hiring-portal/src/Components/Stories.jsx
Labels: level3, gssoc-ext, hacktoberfest, hacktoberfest-accepted

#370 fixes multiple ui issues through out the page
  hiring-portal/src/CSS/faqSection.module.css
  hiring-portal/src/CSS/herosection.module.css
  hiring-portal/src/CSS/jobpage.css
  hiring-portal/src/Components/Jobpage.jsx
  hiring-portal/src/Components/Navbar.jsx
Labels: level2, gssoc-ext, hacktoberfest, hacktoberfest-accepted

#373 Added Hovering Effects on cards !!
  hiring-portal/src/CSS/About.module.css
Labels: level1, gssoc-ext, hacktoberfest, hacktoberfest-accepted
